server:
  port: 8085
spring:
  application:
    name: friendship-service
  datasource:
    password: ${DB_PASSWORD}
    username: postgres
    url: jdbc:postgresql://localhost:5432/friendship_service
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

jwt:
  secret-code: ${SECRET_KEY}

springdoc:
  swagger-ui:
    path: /docs/